9oormthon-univ/2024_DANPOON_TEAM_48_BE

Mesh_backend/src/main/java/com/example/mesh_backend/common/CustomErrorException.java
Mesh_backend/src/main/java/com/example/mesh_backend/common/exception/ErrorCode.java
Mesh_backend/src/main/java/com/example/mesh_backend/config/SecurityConfig.java
Mesh_backend/src/main/java/com/example/mesh_backend/login/controller/UserController.java
Mesh_backend/src/main/java/com/example/mesh_backend/login/dto/request/KakaoSignupRequest.java
Mesh_backend/src/main/java/com/example/mesh_backend/login/dto/request/KakaoTokenRequest.java
Mesh_backend/src/main/java/com/example/mesh_backend/login/dto/response/KakaoTokenResponse.java
Mesh_backend/src/main/java/com/example/mesh_backend/login/dto/response/UserIdResponse.java
Mesh_backend/src/main/java/com/example/mesh_backend/login/entity/MainCategoryName.java
Mesh_backend/src/main/java/com/example/mesh_backend/login/entity/Maincategory.java
Mesh_backend/src/main/java/com/example/mesh_backend/login/entity/Refreshtoken.java
Mesh_backend/src/main/java/com/example/mesh_backend/login/entity/SubCategoryName.java
Mesh_backend/src/main/java/com/example/mesh_backend/login/entity/Subcategory.java
Mesh_backend/src/main/java/com/example/mesh_backend/login/entity/User.java
Mesh_backend/src/main/java/com/example/mesh_backend/login/repository/RefreshtokenRepository.java
Mesh_backend/src/main/java/com/example/mesh_backend/login/repository/UserRepository.java
Mesh_backend/src/main/java/com/example/mesh_backend/login/security/CustomUserDetails.java
Mesh_backend/src/main/java/com/example/mesh_backend/login/security/CustomUserDetailsService.java
Mesh_backend/src/main/java/com/example/mesh_backend/login/security/JwtAuthenticationFilter.java
Mesh_backend/src/main/java/com/example/mesh_backend/login/service/TokenService.java
Mesh_backend/src/main/java/com/example/mesh_backend/login/service/UserService.java
Mesh_backend/src/main/java/com/example/mesh_backend/message/BasicResponse.java

- #이슈번호
- #2 
카카오 oauth 이용한 로그인 및 회원가입, 로그아웃, 회원탈퇴 기능 구현

[feat] 카카오 로그인 및 회원가입 기능 구현

---

Mesh_backend/src/main/java/com/example/mesh_backend/common/exception/ErrorCode.java
Mesh_backend/src/main/java/com/example/mesh_backend/login/entity/MainCategoryName.java
Mesh_backend/src/main/java/com/example/mesh_backend/login/entity/SubCategoryName.java
Mesh_backend/src/main/java/com/example/mesh_backend/login/entity/User.java
Mesh_backend/src/main/java/com/example/mesh_backend/mypage/controller/MypageController.java
Mesh_backend/src/main/java/com/example/mesh_backend/mypage/dto/request/AwardRequest.java
Mesh_backend/src/main/java/com/example/mesh_backend/mypage/dto/request/CareerRequest.java
Mesh_backend/src/main/java/com/example/mesh_backend/mypage/dto/request/ToolRequest.java
Mesh_backend/src/main/java/com/example/mesh_backend/mypage/dto/request/UserProfileRequest.java
Mesh_backend/src/main/java/com/example/mesh_backend/mypage/entity/Award.java
Mesh_backend/src/main/java/com/example/mesh_backend/mypage/entity/Career.java
Mesh_backend/src/main/java/com/example/mesh_backend/mypage/entity/CollaborationTool.java
Mesh_backend/src/main/java/com/example/mesh_backend/mypage/entity/Scale.java
Mesh_backend/src/main/java/com/example/mesh_backend/mypage/entity/Tool.java
Mesh_backend/src/main/java/com/example/mesh_backend/mypage/repository/AwardRepository.java
Mesh_backend/src/main/java/com/example/mesh_backend/mypage/repository/CareerRepository.java
Mesh_backend/src/main/java/com/example/mesh_backend/mypage/repository/ToolRepository.java
Mesh_backend/src/main/java/com/example/mesh_backend/mypage/service/MeshScoreService.java
Mesh_backend/src/main/java/com/example/mesh_backend/mypage/service/MypageService.java

#4 
- #이슈번호
마이페이지 내정보 수정(경력, 관심 키워드,,,), meshscore계산하는 메소드 구현
meshscore는 동료평가 기능이 구현한 후 추가적인 수정이 필요하다.

[feat] 마이페이지 - 내정보 수정 및 메시스코어 기능 수현

---

Mesh_backend/build.gradle
Mesh_backend/src/main/java/com/example/mesh_backend/common/exception/ErrorCode.java
Mesh_backend/src/main/java/com/example/mesh_backend/common/utils/S3Uploader.java
Mesh_backend/src/main/java/com/example/mesh_backend/config/S3Config.java
Mesh_backend/src/main/java/com/example/mesh_backend/config/SecurityConfig.java
Mesh_backend/src/main/java/com/example/mesh_backend/login/controller/UserController.java
Mesh_backend/src/main/java/com/example/mesh_backend/login/service/UserService.java
Mesh_backend/src/main/java/com/example/mesh_backend/mypage/controller/MypageController.java
Mesh_backend/src/main/java/com/example/mesh_backend/mypage/service/MypageService.java
Mesh_backend/src/main/resources/application.yml

- #이슈번호
#8 
프로필 이미지관련해서 aws s3이용해서 저장, 수정, 삭제가 가능하도록 기능 수정

[feat] 유저 프로필 이미지 - aws s3이용

---

Mesh_backend/src/main/java/com/example/mesh_backend/post/controller/PostController.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/dto/PostRequestDTO.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/entity/Post.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/repository/PostRepository.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/service/PostService.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/service/PostServiceImpl.java

- #11 
팀원 공고 등록
이번 PR이후 S3연결 추가 예정

✨ [FEAT] 팀원 모집 공고 등록 API

---

Mesh_backend/src/main/java/com/example/mesh_backend/post/controller/PostSearchController.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/dto/PostResponseDTO.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/repository/PostRepository.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/service/PostService.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/service/PostServiceImpl.java

✨ [feat] 조회수 기반 상위 5개 프로젝트 순위 나열

---

Mesh_backend/.gitignore
Mesh_backend/src/main/java/com/example/mesh_backend/chat/controller/ChatController.java
Mesh_backend/src/main/java/com/example/mesh_backend/chat/controller/ChatScheduleController.java
Mesh_backend/src/main/java/com/example/mesh_backend/chat/controller/ChatSettingsController.java
Mesh_backend/src/main/java/com/example/mesh_backend/chat/controller/MessageController.java
Mesh_backend/src/main/java/com/example/mesh_backend/chat/dto/request/ChatSettingsUpdateRequest.java
Mesh_backend/src/main/java/com/example/mesh_backend/chat/dto/request/MessageRequest.java
Mesh_backend/src/main/java/com/example/mesh_backend/chat/dto/request/ScheduleCreateRequest.java
Mesh_backend/src/main/java/com/example/mesh_backend/chat/dto/request/ScheduleUpdateRequest.java
Mesh_backend/src/main/java/com/example/mesh_backend/chat/dto/response/ChatRoomDetailsResponse.java
Mesh_backend/src/main/java/com/example/mesh_backend/chat/dto/response/ChatSettingsResponse.java
Mesh_backend/src/main/java/com/example/mesh_backend/chat/dto/response/MessageResponse.java
Mesh_backend/src/main/java/com/example/mesh_backend/chat/dto/response/ParticipantResponse.java
Mesh_backend/src/main/java/com/example/mesh_backend/chat/dto/response/ScheduleResponse.java
Mesh_backend/src/main/java/com/example/mesh_backend/chat/entity/ChatRoom.java
Mesh_backend/src/main/java/com/example/mesh_backend/chat/entity/JoinChat.java
Mesh_backend/src/main/java/com/example/mesh_backend/chat/entity/Message.java
Mesh_backend/src/main/java/com/example/mesh_backend/chat/entity/Schedule.java
Mesh_backend/src/main/java/com/example/mesh_backend/chat/respository/ChatroomRepository.java
Mesh_backend/src/main/java/com/example/mesh_backend/chat/respository/JoinChatRepository.java
Mesh_backend/src/main/java/com/example/mesh_backend/chat/respository/MessageRepository.java
Mesh_backend/src/main/java/com/example/mesh_backend/chat/respository/ScheduleRepository.java
Mesh_backend/src/main/java/com/example/mesh_backend/chat/service/ChatScheduleService.java
Mesh_backend/src/main/java/com/example/mesh_backend/chat/service/ChatService.java
Mesh_backend/src/main/java/com/example/mesh_backend/chat/service/ChatSettingsService.java
Mesh_backend/src/main/java/com/example/mesh_backend/chat/service/MessageService.java
Mesh_backend/src/main/java/com/example/mesh_backend/config/SecurityConfig.java

- 채팅방별 설정 기능 구현
- #이슈번호
#18  
- 1대1 채팅 기능 구현 (polling 방식)
- 채팅방별 설정관련 기능 구현
공모전관련 단체톡방은 추후 구현예정

[feat] 일대일 폴링 채팅 기능 구현

---

Mesh_backend/src/main/java/com/example/mesh_backend/common/exception/ErrorCode.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/controller/PostController.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/dto/BackMemberDTO.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/dto/DesignMemberDTO.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/dto/FrontMemberDTO.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/dto/PMMemberDTO.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/dto/PostRequestDTO.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/dto/ProjectUpdateRequestDTO.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/dto/TeamMembersDTO.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/entity/BackMatch.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/entity/DesignMatch.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/entity/FrontMatch.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/entity/PMMatch.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/entity/Post.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/entity/Project.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/entity/Status.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/repository/BackMatchRepository.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/repository/DesignMatchRepository.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/repository/FrontMatchRepository.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/repository/PMMatchRepository.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/repository/PostRepository.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/repository/ProjectRepository.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/service/PostService.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/service/PostServiceImpl.java

- #17 
팀원 매칭시 각 매칭 테이블 저장 + project 테이블 저장
공고 이미지, 파일 S3연결 추가

[FEAT] 모집공고 업로드, 수정, 팀원 매칭 API

---

Mesh_backend/src/main/java/com/example/mesh_backend/apply/controller/ApplyController.java
Mesh_backend/src/main/java/com/example/mesh_backend/apply/dto/ApplyRequestDTO.java
Mesh_backend/src/main/java/com/example/mesh_backend/apply/entity/Apply.java
Mesh_backend/src/main/java/com/example/mesh_backend/apply/entity/Part.java
Mesh_backend/src/main/java/com/example/mesh_backend/apply/repository/ApplyRepository.java
Mesh_backend/src/main/java/com/example/mesh_backend/apply/service/ApplyService.java
Mesh_backend/src/main/java/com/example/mesh_backend/apply/service/ApplyServiceImpl.java

- #23 
apply 테이블을 따로 만들어서 지원 누를시 저장됨.
url에서 project_id 가져옴
user는 토큰에서 가져옴
create_At은 자동 local 에서 가져옴

[Feat] 팀지원하기 API

---

Mesh_backend/src/main/java/com/example/mesh_backend/apply/controller/ApplyController.java
Mesh_backend/src/main/java/com/example/mesh_backend/apply/entity/Apply.java
Mesh_backend/src/main/java/com/example/mesh_backend/apply/service/ApplyServiceImpl.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/repository/PostRepository.java

- #23 
- 팀 지원하기 url 매핑 변경
- leader_id post에서 가져와서 매핑

[Fix] leader(post작성자) id 추가 변경

---

Mesh_backend/src/main/java/com/example/mesh_backend/chat/controller/ChatSettingsController.java

[feat] 스웨거 어노테이션 추가

---

Mesh_backend/src/main/java/com/example/mesh_backend/mark/controller/MarkController.java
Mesh_backend/src/main/java/com/example/mesh_backend/mark/entity/Mark.java
Mesh_backend/src/main/java/com/example/mesh_backend/mark/repository/MarkRepository.java
Mesh_backend/src/main/java/com/example/mesh_backend/mark/service/MarkService.java
Mesh_backend/src/main/java/com/example/mesh_backend/mark/service/MarkServiceImpl.java

- #28 
같은 API호출시 있으면 삭제, 없으면 등록됨

[Feat] 북마크 등록/삭제 API

---

Mesh_backend/src/main/java/com/example/mesh_backend/mark/repository/MarkRepository.java
Mesh_backend/src/main/java/com/example/mesh_backend/mypage/controller/MypageController.java
Mesh_backend/src/main/java/com/example/mesh_backend/mypage/dto/response/ProjectDetailResponse.java
Mesh_backend/src/main/java/com/example/mesh_backend/mypage/dto/response/ProjectResponseDTO.java
Mesh_backend/src/main/java/com/example/mesh_backend/mypage/service/MypageProjectService.java
Mesh_backend/src/main/java/com/example/mesh_backend/mypage/service/MypageProjectServiceImpl.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/repository/PostRepository.java

- #17 
마이페이지에서 검색하는 것은 조회수는 업데이트 되지 않음

[Feat] 마이페이지에서 참여하는 프로젝트 목록, 상세 목록 조회API

---

Mesh_backend/src/main/java/com/example/mesh_backend/login/repository/UserRepository.java
Mesh_backend/src/main/java/com/example/mesh_backend/mypage/controller/MypageEvaluationController.java
Mesh_backend/src/main/java/com/example/mesh_backend/mypage/dto/request/PeerEvaluationRequest.java
Mesh_backend/src/main/java/com/example/mesh_backend/mypage/dto/response/PeerEvaluationResponse.java
Mesh_backend/src/main/java/com/example/mesh_backend/mypage/service/MypageEvaluationService.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/repository/ProjectRepository.java

- #34 
method부분에서 이전 mesh_score부분이랑 같이 하면 매번 저장할 때마다 불필요하게 호출이 발생하는 것 같아서 우선 따로 분리해서 구현해두었습니다.

[Feat] 동료평가 API

---

Mesh_backend/src/main/java/com/example/mesh_backend/login/controller/UserController.java

- #이슈번호
#36 
카카오 로그인 및 회원가입 액세스토큰으로 이루어지도록 코드 수정

[feat] 액세스 토큰으로 구현되도록 수정

---

Mesh_backend/src/main/java/com/example/mesh_backend/post/entity/PostMainCategory.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/repository/PostRepository.java
Mesh_backend/src/main/java/com/example/mesh_backend/search/controller/SearchController.java
Mesh_backend/src/main/java/com/example/mesh_backend/search/service/SearchService.java

- #33 
키워드 기반 검색 search
- post 카테고리 추가 이후 카테고리 키워드 기반 검색 기능 추가 예정

[Feat] 검색기능 API (일부)

---

Mesh_backend/src/main/resources/application.yml

[feat] rds update로 변경

---

Mesh_backend/src/main/java/com/example/mesh_backend/login/controller/UserController.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/entity/PostMainCategory.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/repository/PostRepository.java
Mesh_backend/src/main/java/com/example/mesh_backend/search/controller/SearchController.java
Mesh_backend/src/main/java/com/example/mesh_backend/search/service/SearchService.java
Mesh_backend/src/main/resources/application.yml

[feat] develop -> main

---

Mesh_backend/src/main/java/com/example/mesh_backend/chat/controller/MessageController.java
Mesh_backend/src/main/java/com/example/mesh_backend/mypage/entity/Career.java

[feat] chat 부분 수정

---

Mesh_backend/src/main/java/com/example/mesh_backend/post/dto/PostRequestDTO.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/entity/BackCategory.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/entity/DesignCategory.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/entity/FrontCategory.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/entity/PMCategory.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/entity/Post.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/repository/BackCategoryRepository.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/repository/DesignCategoryRepository.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/repository/FrontCategoryRepository.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/repository/PMCategoryRepository.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/service/PostServiceImpl.java

[Fix] category 다중 입력 수정

---

Mesh_backend/src/main/java/com/example/mesh_backend/login/controller/UserController.java

[feat] 회원가입 로직 통합

---

Mesh_backend/src/main/java/com/example/mesh_backend/post/entity/Post.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/repository/PostRepository.java
Mesh_backend/src/main/java/com/example/mesh_backend/search/controller/SearchController.java
Mesh_backend/src/main/java/com/example/mesh_backend/search/dto/ProjectResponseDTO.java
Mesh_backend/src/main/java/com/example/mesh_backend/search/service/SearchService.java

- #33 
카테고리 설정시 해당 카테고리 갖고 있는 결과 나열하기
여러개 설정시 중복&& 하여 갖고 있도록 구현함
response시 해당 게시글이 어떤 main 카테고리를 갖고 있는지 함께 출력 -> 프론트엔드에서 필터링 가능

[Fix] 카테고리 설정하여 검색 

---

Mesh_backend/src/main/java/com/example/mesh_backend/login/controller/UserController.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/entity/Post.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/repository/PostRepository.java
Mesh_backend/src/main/java/com/example/mesh_backend/search/controller/SearchController.java
Mesh_backend/src/main/java/com/example/mesh_backend/search/dto/ProjectResponseDTO.java
Mesh_backend/src/main/java/com/example/mesh_backend/search/service/SearchService.java

[feat] dvelop -> main

---

Mesh_backend/src/main/java/com/example/mesh_backend/post/controller/PostSearchController.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/dto/PostResponseDTO.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/service/PostService.java
Mesh_backend/src/main/java/com/example/mesh_backend/post/service/PostServiceImpl.java

- #12 
기존 title만 나열 -> 필요 정보 나열

[Fix] 프로젝트 상위 5개 정보 추가

---

Mesh_backend/src/main/java/com/example/mesh_backend/search/controller/SearchController.java
Mesh_backend/src/main/java/com/example/mesh_backend/search/dto/ProjectDetailResponse.java
Mesh_backend/src/main/java/com/example/mesh_backend/search/service/SearchService.java

- #이슈번호
- #33 
프로젝트 상세 조회 + 조회수 증가

[Feat] 프로젝트 상세 조회 API + 조회수 증가

---

Mesh_backend/src/main/java/com/example/mesh_backend/mypage/controller/MypageController.java
Mesh_backend/src/main/java/com/example/mesh_backend/mypage/dto/response/ProjectResponseDTO.java
Mesh_backend/src/main/java/com/example/mesh_backend/mypage/service/MypageProjectService.java
Mesh_backend/src/main/java/com/example/mesh_backend/mypage/service/MypageProjectServiceImpl.java

- #56 
마이페이지에서 내가 참여하는 프로젝트 리스트 조회할 때 d-day동료평가도 함께 response해주는 것으로 수정함
이렇게 되면 0일 때는 프론트에서 활성화 시키지 않고, 0이 아닐 때는 활성화 시키면 됨!

[Fix] 마이페이지 목록 d-day추가

---

Mesh_backend/src/main/java/com/example/mesh_backend/mark/controller/MarkController.java
Mesh_backend/src/main/java/com/example/mesh_backend/mark/repository/MarkRepository.java
Mesh_backend/src/main/java/com/example/mesh_backend/mark/service/MarkService.java
Mesh_backend/src/main/java/com/example/mesh_backend/mark/service/MarkServiceImpl.java

- #28 
bookmark가 true인 프로젝트 공고 목록 조회 추가

[Feat] 북마크 된 목록만 조회 API

---

Mesh_backend/src/main/resources/application.yml

[feat] 서버 80 변경
